config/routes.rb
Rails.application.routes.draw do

  
#Customer
  root to: 'pages#index'
  get 'about', to: 'pages#about'
  get 'coupons/checking/:code', action: :checking, controller: 'coupons'
  post 'cekstatus', to: 'cart_products#check'

  resource :comments
  # resources :users, only: [:edit, :update]
  resources :users, only: :index do
    collection do
      get 'profile'
      put 'update'
    end
  end

  resources :wallet_statuses
  resources :carts do
    member do
      post 'create_transaction'
      post 'change_quantity'
    end
  end 
  
  resources :orders do
    member do
      patch 'cancel'
      patch "transition"
    end
  end

  resources :cart_products do
    member do
      post :change_quantity
    end
  end
  
  resources :notifications, only: [:index]

  devise_for :users
  resources :products do
    member do
        post 'add_cart_product'
        post 'create_comment'
      end
    end
  
  


	#ADMIN
	namespace :admins do
		get 'pages/index' => 'pages#index'
		resources :products do
      member do
        post "create_comment"
        patch 'set_active'
        patch 'set_deactive'
      end
    end

    resources :orders, except: [:new, :destroy] do
       member do
        get "input_receiver"
        get "input_receipt" 
        patch "transition"
      end
    end
    resources :notifications, only: [:index, :show]
    resources :extra_charges, only: [:edit, :update]

		resources :coupons
    resources :service_charges 
    resources :wallet_statuses, only: [:index, :edit, :update] do
      member do 
        patch 'success'
        patch 'failed'
      end
    end
	end
  end

app/helpers/admins/transactions_helper.rb
module Admins::TransactionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= simple_form_for @transaction do |f| %>
    <div class="row">
      <%= f.simple_fields_for :transaction_detail do |p| %>
        <div class="col-lg-8 col-md-6">
            <div class="row">
                <div class="col-lg-12">
                  <%= f.input :recipient_name %>
                </div>
            </div>
            <div class="checkout__input">
                <p>Country<span>*</span></p>
                <input type="text">
            </div>
            <div class="checkout__input">
                <p>Address<span>*</span></p>
                <input type="text" placeholder="Street Address" class="checkout__input__add">
                <input type="text" placeholder="Apartment, suite, unite ect (optinal)">
            </div>
            <div class="checkout__input">
                <p>Town/City<span>*</span></p>
                <input type="text">
            </div>
            <div class="checkout__input">
                <p>Country/State<span>*</span></p>
                <input type="text">
            </div>
            <div class="checkout__input">
                <p>Postcode / ZIP<span>*</span></p>
                <input type="text">
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="checkout__input">
                        <p>Phone<span>*</span></p>
                        <input type="text">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="checkout__input">
                        <p>Email<span>*</span></p>
                        <input type="text">
                    </div>
                </div>
            </div>
            <div class="checkout__input">
              <%= f.input :note, label: 'Order Notes', placeholder: "Notes about your order, e.g. special notes for delivery.s" %>
            </div>
        </div>
      <%end%>
        <div class="col-lg-4 col-md-6">
            <div class="checkout__order">
                <h4>Your Order</h4>
                <div class="checkout__order__products">Products <span>Total</span></div>
                  <ul>
                  <%@transaction.cart.cart_products.each do |product|%>
                    <li><%=product.product.name.capitalize%><span><%=number_to_currency(product.quantity * product.product.price , :locale => :id)%></span></li>
                  <%end%>
                  </ul>
                  <div class="postal_fee">Postal Fee <span><%=number_to_currency(@transaction.postal_fee.price, :locale => :id)%></span></div>
                <div class="checkout__order__subtotal">Subtotal <span><%=number_to_currency(@transaction.total_price, :locale => :id)%></span></div>
                  
                <div class="checkout__input__checkbox">
                <button type="submit" class="site-btn">PLACE ORDER</button>
            </div>
        </div>
    </div>
<%end%>

app/views/transactions/index.html.erb
<div class="alert alert-info"><%= notice %></div>

<h1>Transactions</h1>
</br>
    <%= search_form_for @q, url: transactions_path do |f| %> 
    <div class="row" style="padding-left: 780px">
      <div class="col-md-4">
        <%= f.select :status_eq, options_for_select([["All", ""], ["Active", "active"], ["Processed", "processed"],["Delivery", "delivery"],["Delivered", "delivered"], ["Finished", "finished"], ["Cancelled", "cancelled"]], selected: @q.status_eq), {}, { :class => "form-control" }%>
      </div>
      <div class="col-md-2">
        <%= f.button :Search, class: 'site-btn btn-sm', style: 'height:38px'%>     
      </div>
  </div>
    </div>
    <%end%>
  </br>

<table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Order Date</th>
      <th class="th-sm">Product Purchased</th>
      <th class="th-sm">Total price</th>
      <th class="th-sm">Order status</th>
      <th class="th-sm">Check Detail</th>
    </tr>
  </thead>

  <tbody>
   <% @transactions.each do |transaction| %>
      <tr>
       <td><%= transaction.created_at.strftime("%A, %d-%m-%Y") %></td>
        <td><%= transaction.cart.products.count %></td>
        <td><%= number_to_currency(transaction.total_price, locale: :id)%></td>
        <td><%= transaction.status.titleize %></td>
        <td><%= link_to 'Detail', transaction_path(transaction), class: 'btn btn-secondary'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
$(document).ready(function () {
$('#dtBasicExample').DataTable();
$('.dataTables_length').addClass('bs-select');
});
</script>

app/views/transactions/show.html.erb
<div class="container">
	<h3>Transaction Detail</h3>
	<div class="row">
        <div class="col-lg-6 col-md-6">
			<p>
			  <strong>Order Date:</strong>
			  <%= @transaction.created_at.strftime("%A, %d-%m-%Y") %>
			</p>
			<p>
			  <strong>Total Price:</strong>
			  <%= number_to_currency(@transaction.total_price, :locale => :id) %>
			</p>
			<p>
			  <strong>Status:</strong>
			  <%= @transaction.status.titleize %>
			</p>
			<p>
			  <strong>Product:</strong>
			  	<table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
				  	<thead>
				    	<tr>
				      		<th class="th-sm">Name</th>
						    <th class="th-sm">Price</th>
						    <th class="th-sm">Total Item</th>
						    <th class="th-sm">Image</th>
				    	</tr>
				  	</thead>
				  	<tbody>
					  	<% @transaction.cart.products.group_by(&:itself).uniq.each do |tp,v| %>
					  	<tr>
					  		<td><%= tp.name %></td>
					  		<td><%= number_to_currency(tp.price, :locale => :id) %></td>
					  		<td><%= v.count %></td>
					  		<td><%= image_tag tp.image_url %></td>
					  	</tr>
					  	<% end %>
					</tbody>
				</table>
			</p>
			<%= link_to 'Back', transactions_path, class: 'btn btn-sm btn-success' %>
			<%if @transaction.active? %>
				<%= link_to 'Cancel Transaction', cancel_transaction_path(@transaction), class: 'btn btn-sm btn-danger' %>
			<%end%>
	</div>
</div>